repos:
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: v4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]  # Example of adding extra dependencies to flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        files: \.py$
        
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort (Python imports sorter)
